name: Generate Pacman Animation

on:
  # รันอัตโนมัติทุกๆ 24 ชั่วโมง
  schedule:
    - cron: "0 */24 * * *" 
  
  # อนุญาตให้กดรันเองได้จากแถบ Actions
  workflow_dispatch:
  
  # รันทุกครั้งที่มีการ Push โค้ดใหม่ลงใน Branch main
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # สร้างไฟล์ Pacman SVG จากข้อมูล Contribution
      - name: generate pacman-contribution-graph.svg
        uses: platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman-contribution-graph.svg?color_snake=#fdb813&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39&snake_type=pacman
            dist/pacman-contribution-graph-dark.svg?color_snake=#fdb813&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353&snake_type=pacman&palette=github-dark
          
      # นำไฟล์ SVG ที่สร้างเสร็จแล้วไปเก็บไว้ใน Branch ชื่อ 'output'
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
