name: Generate Pacman

on:
  schedule: # รันทุก 12 ชั่วโมง
    - cron: "0 */12 * * *" 
  workflow_dispatch: # กดรันเองได้

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman Graph
        uses: platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
